# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#121212"

# Main text color
theme[main_fg]="#e0e0e0"

# Title color for boxes
theme[title]="#e0e0e0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E87D3E"

# Background color of selected item in processes box
theme[selected_bg]="#632523"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#424242"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#e0e0e0"

# Background color of the percentage meters
theme[meter_bg]="#424242"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e0e0e0"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#E87D3E"
theme[mem_box]="#9E1B32"
theme[net_box]="#632523"
theme[proc_box]="#E87D3E"

# Box divider line and small boxes line color
theme[div_line]="#424242"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#e0e0e0"
theme[temp_mid]="#E87D3E"
theme[temp_end]="#9E1B32"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#632523"
theme[cpu_mid]="#9E1B32"
theme[cpu_end]="#E87D3E"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#E87D3E"
theme[free_mid]="#9E1B32"
theme[free_end]="#632523"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#632523"
theme[cached_mid]="#9E1B32"
theme[cached_end]="#E87D3E"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#E87D3E"
theme[available_mid]="#9E1B32"
theme[available_end]="#632523"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#632523"
theme[used_mid]="#9E1B32"
theme[used_end]="#E87D3E"

# Download graph colors (Peach -> Red)
theme[download_start]="#E87D3E"
theme[download_mid]="#9E1B32"
theme[download_end]="#632523"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#632523"
theme[upload_mid]="#9E1B32"
theme[upload_end]="#E87D3E"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#632523"
theme[process_mid]="#9E1B32"
theme[process_end]="#E87D3E"
